LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="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"
LANGCHAIN_PROJECT="gemini_chatbot"
GOOGLE_API_KEY="AIzaSyCxDjzky8-4gZ-rUuhU9oxZOgXujZFTokc"